title: PICT-2020-SERIEA_03903
description: Datos de investigaci√≥n
baseurl: "/pict-glotales"
url: "https://dila-ling.github.io"
github_repo: pict-glotales
github_username: dila-ling

instagram_username: dila.imhicihu.ok
social_link: twitter
twitter_username: DilaConicet


theme_color: pict

markdown: kramdown

plugins:
   - jekyll-sitemap
   - jekyll-seo-tag

navigation:
  - {name: 'Corpus', link: '/corpus'}
  - {name: 'Resultados', link: '/resultados'}
  - {name: 'Mapa de fuentes', link: '/mapa'}

collections:
  fuentes:
     output: true
  lex:
     output: true

defaults:
  - scope:
      path: "assets/audio"
    values:
      wav: true

exclude:
  - Gemfile
  - Gemfile.lock
